# Site settings
title: Adam Kucharski
header-img: ""
email: ""
description: "Adam Kucharski"
baseurl: "" # Check not an issue
url: "http://kucharski.io"
twitter_username: AdamJKucharski
github_username:  adamkucharski
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate_path: "page:num"
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
